### PR TITLE
Config encryption

### PR DESCRIPTION
**Pull request by ElectricErudite**
To enable config encryption this PR should be accepted with the other PRs for common and configuration. 

The EncryptFile class is being replaced by a combination of new classes. Encryption is handled by the new CmsEncryptor class. Loading key files is now handled by the KeyLoader class, and Hashing is conducted by the new CmsHasher class. 

Encryption of the configuration attributes is handled by the cms config encrypt command. 
Attributes are selected by regular expressions that are within the new cloudmesh.security section of the cloudmesh.yaml file (introduced in complementary configuration PR). 

For more details please reference this [report.md](https://github.com/cloudmesh-community/fa19-516-144/blob/master/project/report.md).

### CODE REVIEW

**Comment by ElectricErudite** [comment]
Encryption reliant upon the approval of this PR and the approval of 
[configuration PR](https://github.com/cloudmesh/cloudmesh-configuration/pull/2)
[common](https://github.com/cloudmesh/cloudmesh-common/pull/10)

**Comment by laszewsk** [comment]
Also I do not yt know about this error

Collecting base64 (from cloudmesh-cloud==4.1.5)
  Could not find a version that satisfies the requirement base64 (from cloudmesh-cloud==4.1.5) (from versions: )
No matching distribution found for base64 (from cloudmesh-cloud==4.1.5)
The command "pip install ." failed and exited with 1 during .

**Comment by ElectricErudite** [comment]
> this is too much for the commandline, you need to put the code in encrypt and decryot in a class or file outside the comamnd

Since they don't take any arguments I could migrate all of the encryption and decryption commands directly into the Config class by introducing new encrypt() and decrypt() functions. 

This could change the encrypt case to 
  elif arguments.encrypt:
      config = Config()
      config.encrypt()
and the decryption case to 
  elif argumenst.decrypt:
      config = Config()
      config.decrypt() 

How does that change sound? 

> Also I do not yt know about this error
> 
> Collecting base64 (from cloudmesh-cloud==4.1.5)
> Could not find a version that satisfies the requirement base64 (from cloudmesh-cloud==4.1.5) 
> (from versions: )
> No matching distribution found for base64 (from cloudmesh-cloud==4.1.5)
> The command "pip install ." failed and exited with 1 during .

I will look into the error.

**Comment by ElectricErudite** [comment]
> Also I do not yt know about this error
> 
> Collecting base64 (from cloudmesh-cloud==4.1.5)
> Could not find a version that satisfies the requirement base64 (from cloudmesh-cloud==4.1.5) 
> (from versions: )
> No matching distribution found for base64 (from cloudmesh-cloud==4.1.5)
> The command "pip install ." failed and exited with 1 during .

That is a mistaken pip requirement. I should not have added that. base64 is part of the python base install and only requires an 'import' statement. This is why the error is occurring. 
I'll add changes to remove with the other changes to move the encrypt and decrypt command handling.

**Comment by ElectricErudite** [comment]
> this is too much for the commandline, you need to put the code in encrypt and decryot in a class or file outside the comamnd

The encryption and decryption command handling was migrated to the Config class. 
Since the code was migrated [this](https://github.com/cloudmesh/cloudmesh-cloud/pull/245/commits/198c6dcbb1faaddf2031c7bd1113799c3e731656) commit deletes the now redundant lines.

**Pull request merged**
