### PR TITLE
Feature/mongo install fix

### PR DESCRIPTION
**Pull request by kennethj**
https://github.com/cloudmesh/cloudmesh-cloud/blob/master/cloudmesh/mongo/MongoDBController.py#L45
```
self.mongo_code = path_expand(download["url"])
```

Causing a `string indices must be integers` error.

- [x] Refactor to use map syntax to retrieve config properties

### CODE REVIEW

**Comment by laszewsk** [comment]
The error may indicate you have an outdated yaml file?

**Comment by kennethj** [comment]
What yaml version works for the current system? I have `version: 4.1.4` in the yaml file generated via `cms init yaml` earlier this semester.

**Comment by laszewsk** [comment]
4.1.7

**Comment by laszewsk** [comment]
please use the 

cms config check program that tells you the current version, naturallly use 

cd cm
cloudmesh-installer git pull cloud

to get the newest version.

you need to do the modifications by hand as we do not want to overwrite your current yaml file

**Comment by laszewsk** [comment]
have you been able to confirm instalation

**Comment by laszewsk** [comment]
we believe this is caused because the cloudmesh code is old and the yaml file is not of the new format. If this is not the case, please reopen. we close this issue now based on consulation in the group

**Pull request closed without merging**
