### PR TITLE
integrate vagrant module with cm4

### PR DESCRIPTION
**Pull request by kimballXD**

### CODE REVIEW

**Comment by laszewsk** [comment]
can you comment on how you manage the vms 

e.g. are you doing it like i did, e.g. a dir for each vm with its vagrant file or something else?

**Comment by kimballXD** [comment]
I believe from the very beginning there is always one Vagrnatfile to handle All vms (which Vagrantfile should be saved at `~/.cloudmesh/vagrant_workspace/Vagrnatfile`), since Vagrant can only handle one Vagrantfile at a time. If you use multiple Vagrantfile and one Vagrantfile for a single VM, then when you issue `cm4 vagrant list`, you can only get infos for one VM instead of all vms.

**Comment by laszewsk** [comment]
good analysis, this means we go with my approach to place it for each vm in ~/.cloudmesh/cagrant/NAMEOFVM

As we can than store that info in mongo we just cycle through either the vagrant files or simply use virtualboxmanage directly. We get the state form mongo, but have a refersh that loads the state into mongo

**Comment by laszewsk** [comment]
lets revisit https://github.com/cloudmesh/vagrant in addition to what you did

**Pull request merged**
